### PR TITLE
Added python3.9libs

### PR DESCRIPTION
**Pull request by andreasmalta1**
This makes SG integration for the latest version of Houdini 19.5.303 running python 3.9 possible.

### CODE REVIEW

**Comment by rallymatte** [comment]
any particular reason this hasn't been merged yet?

**Comment by brettmaker** [comment]
What's the ETA on merging this in?

**Review by julien-lang — APPROVED** [review]
LGTM!

**Comment by julien-lang** [comment]
Thanks for the PR, it has been merged with a few other changes in #64.

**Pull request closed without merging**
