### PR TITLE
Don't destroy engine when file is outside project

### PR DESCRIPTION
**Pull request by eprana**
Print warning in log & return

### CODE REVIEW

**Comment by aoblet** [comment]
Hello Guys,
Any chance to have a feedback on that ?

Thanks

**Comment by jfboismenu** [comment]
Hi!

Sorry for the late response. May I ask what is the workflow you are trying to solve with this change?

`automatic_context_switching` is meant to be used when using the Toolkit templating system. Destroying the engine and disabling Toolkit when an opened file does not match any context is standard behaviour in all Toolkit engines. With such a file, the `publish2` app can't publish your work and `workfiles2` would likely bug out as well.

If we were to change this behaviour, we would have to consider the impact of this change on existing workflows, update apps accordingly and make the modification to all engines.

**Comment by eprana** [comment]
Hi ! 
Our issue is that when a file that does not match any context is opened, the function sgtk.platform.current_engine() return None. 
We have this behavior only with tk-houdini. 
For instance, in Maya, the Shotgun menu is also disabled, but an engine is returned.

So this may not be the right place to fix this, but we already had the fix in the previous pull request :)

**Comment by jfboismenu** [comment]
Sorry, I may have misinterpreted that other PR. I'll reopen it and bring this to the team's attention.

**Comment by jfboismenu** [comment]
Hi, we won't be able to accept the PR in this state. The problem is that when an invalid file is opened the Toolkit menu should be disabled, which is not the case anymore with this PR. We should probably update the logic [here](https://github.com/shotgunsoftware/tk-houdini/blob/01f311e92fda06c7a29f78dab32a1a5085ec0013/python/tk_houdini/ui_generation.py#L1169-L1179) so that current engine is always assumed to be there but something else tells the code that Toolkit should be disabled. Maybe the engine can have a `is_sgtk_disabled` property that is initially `False` and is set to the right value on file change? The code I've linked to would look at that flag instead.

If you're uncomfortable doing this change, don't have time, or are fine with using your current fix, we'll log a ticket to fix this on our end, but we can't promise when we get to fix this.

**Comment by eprana** [comment]
@jfboismenu We will wait for a fix then :)
Thank you for your feedback.

**Comment by jfboismenu** [comment]
Alright, we'll close this PR and come back when we have an official fix.

**Pull request closed without merging**
