### PR TITLE
Don't destroy engine when current file is outside project

### PR DESCRIPTION
**Pull request by alefeve**

### CODE REVIEW

**Comment by eprana** [comment]
Any update bout this Merge Request ?

**Comment by jfboismenu** [comment]
Superceded by https://github.com/shotgunsoftware/tk-houdini/pull/49

**Comment by jfboismenu** [comment]
Closed by mistake.

**Comment by jfboismenu** [comment]
See comments on https://github.com/shotgunsoftware/tk-houdini/pull/49 for the merge-ability of this PR.

**Comment by jfboismenu** [comment]
As discussed in the other pull request, we can't merge these fixes and the Toolkit team will work on a proper fix at some point.

**Pull request closed without merging**
